### ISSUE TITLE
Outdated Version Error albeit most recent Version

### ISSUE THREAD

**Issue by stoerdebegga** [pixelfed/pixelfed-rn#100]
After providing the instance for the login the offical app presented me with an incorrect version warning in the sense that the app considers the instance running on an outdated version.

Neither is true for the instance I am using nor for [pixelfed.social](https://pixelfed.social) but for both the warning is produced.

This also prevents me from using the app entirely as one cannot proceed with the login.

![pixelfed-app-error](https://github.com/user-attachments/assets/8fd59e96-1b38-4f0e-85d7-29978a03db16)

![instance-website](https://github.com/user-attachments/assets/5a237c7f-0b8d-41e1-906d-6d92de2937f2)

**Comment by vwbusguy** [comment]
I'm seeing this today when trying to post to pixelfed.social via this app.

![Screenshot_20240817-083350_Pixelfed](https://github.com/user-attachments/assets/094114ca-d948-49f8-9572-72d7f58a431d)

**Comment by vwbusguy** [comment]
This fixed it for me:

https://github.com/pixelfed/pixelfed-rn/issues/76#issuecomment-2212575041

**Comment by stoerdebegga** [comment]
Thanks for the hint, unfortunately it's not an option as I have installed the app via the F-Droid repository which apparently does not ship any newer version.

Just taking from the URL provided by @dansup this is a build in testing and not yet officially released, hence probably not yet pushed to F-Droid.

**Comment by dansup** [comment]
> Thanks for the hint, unfortunately it's not an option as I have installed the app via the F-Droid repository which apparently does not ship any newer version.
> 
> Just taking from the URL provided by @dansup this is a build in testing and not yet officially released, hence probably not yet pushed to F-Droid.

That is an old version of the app, you can download the latest version on our F-Droid repo [https://fdroid.pixelfed.net/fdroid/repo/](https://fdroid.pixelfed.net/fdroid/repo/)
