### ISSUE TITLE
Can't scroll up/down on carousel

### ISSUE THREAD

**Issue by earth-walker** [pixelfed/pixelfed-rn#11]
When sliding my finger up or down on a carousel, the carousel moves forward or back, but the page does not scroll. If the carousel takes up the whole page because the images are vertically oriented, scrolling the page becomes impossible.

This behavior only occurs when the page is at rest; if it is already scrolling by momentum, any sliding gesture made overtop of a carousel will scroll the page.

**Comment by dansup** [comment]
Fixed in latest commits!
