### ISSUE TITLE
Bug: boosting crashes the app

### ISSUE THREAD

**Issue by Skivling** [pixelfed/pixelfed-rn#110]
I recently updated the app and noticed the boost button was added back! I eagerly pressed it... then the app crashed. 
100% fail rate with 10 tries on different posts. 

It's most likely a problem with the backend being a different version that what the app expects, and I am not on pixelfed.social.

**Comment by dansup** [comment]
Which server are you on?

**Comment by Skivling** [comment]
pixelfed.nz - v0.12.3

**Comment by Skivling** [comment]
Android on the latest Google Play version

**Comment by dansup** [comment]
Fixed in v1.0.0.67
