### ISSUE TITLE
tags with special characters are not fully highlighted 

### ISSUE THREAD

**Issue by ymau** [pixelfed/pixelfed-rn#12]
Tags that contain special characters like german umlauts are not fully highlighted.

![Screenshot_2024-06-26-15-11-51-836_com pixelfed android](https://github.com/pixelfed/pixelfed-rn/assets/13555599/061e1e0a-5ed4-4135-a86a-df1422da653a)

OS: Android

**Comment by dansup** [comment]
Fixed in the latest commits!
