### ISSUE TITLE
Profile loading issue

### ISSUE THREAD

**Issue by Monstanner** [pixelfed/pixelfed-rn#129]
As described in the title, the Android app falls apart. The bug from issue [#70](https://github.com/pixelfed/pixelfed-rn/issues/70) is again or still present. Unfortunately, my comment on this was not answered.

There are two workarounds for this:
1. You open the profile > see a "blank" page > switch to the home screen > switch back to the app > now see the profile
2. You open the profile > see a "blank" page > tap somewhere and hope to hit something > go back > now see the profile.

It should be noted that this blank page is only visually blank. As noted in the second Workaround, the navigation elements are all present.

The second issue is that it happens that the latest post(s) disappear from the feed. However, they are present on the profile. No workaround, apart from having to go to the profile.

The last issue may not be a issue, but it happens that sometimes the app doesn't let you in and wants you to log in again. This can also be related to updating the server. If this is the case, it should be communicated. Either as a maintenance post or as a message in the app if it doesn't receive a response from the server.

I don't know if this is necessary, but these errors occur on Android 13/14 Vanilla with Pixelfed 1.0.0.68.

**Comment by dansup** [comment]
@Monstanner What pixelfed server are you on?

**Comment by Monstanner** [comment]
> @Monstanner What pixelfed server are you on?

pixelfed.social

**Comment by dansup** [comment]
This is fixed in v1.0.0.69 which is being rolled out as we speak!
