### ISSUE TITLE
Confusing UX on New Post page

### ISSUE THREAD

**Issue by CubeOfCheese** [pixelfed/pixelfed-rn#26]
![Screenshot_20240626_204011_pixelfed](https://github.com/pixelfed/pixelfed-rn/assets/16740469/c46ebdbc-8d44-4648-a29d-c6a2330b30cb)
I tried tapping these icons several times before I noticed the actual buttons. 
I'd recommend making them both function as buttons since they look exactly the same as the actual buttons

**Comment by piratenpanda** [comment]
To be honest the int looks more like a button than the buttons themselves
