### ISSUE TITLE
Tap profile pic to open profile not working

### ISSUE THREAD

**Issue by earth-walker** [pixelfed/pixelfed-rn#37]
In the feed view, tapping the profile picture or display name associated with a post navigates to a blank screen.

Tapping the post's hamburger menu and selecting "view profile" works as expected.
![Screenshot_20240628_094443](https://github.com/pixelfed/pixelfed-rn/assets/97205490/85b48099-b627-44b4-b176-b22260c86769)
![Screenshot_20240628-094501_pixelfed](https://github.com/pixelfed/pixelfed-rn/assets/97205490/a3ccecc5-7c5c-43ed-9844-a7ba36773206)

**Comment by earth-walker** [comment]
After restarting the app it seems to be working fine now. Closing

**Comment by kgSignal** [comment]
I am currently experiencing this issue. I force closed and cleared app cache and the profile views still do not work.

Pixel 7Pro with June security update.
