### ISSUE TITLE
Blocked Accounts list is unclickable

### ISSUE THREAD

**Issue by justdaj** [pixelfed/pixelfed-rn#44]
When looking at a list of blocked account, you can not click on an account to view the profile (and therefore unblock it).

1. Proffie Option (bottom right)
2. Hamburger Menu too right
3. Privacy & Relationships
4. Blocked Accounts

v1.0.0.45

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by justdaj** [comment]
Not fixed in V1.0.0.50
