### ISSUE TITLE
Missing Boost Button/icon

### ISSUE THREAD

**Issue by RiversideBryan** [pixelfed/pixelfed-rn#49]
There isn't a boost (re-blog) option/button/icon.

**Comment by justdaj** [comment]
I was just coming on to log the same issue. 😏

**Comment by crimperman** [comment]
Android/1.0.0.50: I can see boosts/shares but there is no boost/share button on posts.

**Comment by weddige** [comment]
> Android/1.0.0.50: I can see boosts/shares but there is no boost/share button on posts.

Than this is might be just https://github.com/pixelfed/pixelfed/issues/4906. I assumed it's not supported in the app, because there is no option do switch boosts on/off.
