### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by aneillans** [pixelfed/pixelfed-rn#5]
Assuming this is the code base that is used for the current iOS Test Flight release? 

If so there is a long running issue where the admin section is not accessible on most platforms, and you encounter an error which simply reports that the Pixelfed instance is not compatible. Given the lack of other (easy) administrative options (and notifications) for instances, this is rather important, so would be great if this could be fixed :)

**Comment by dansup** [comment]
Shipped in the lastest commits!
