### ISSUE TITLE
Liking a post makes the feed move

### ISSUE THREAD

**Issue by MarcoFrasca** [pixelfed/pixelfed-rn#57]
iOS app

When I like a post, the feed moves down just a little bit or sometimes in a different position.

Two examples:

https://github.com/pixelfed/pixelfed-rn/assets/38420974/3c5308d0-77c1-4e93-83a3-bcf6aaa53e8f

https://github.com/pixelfed/pixelfed-rn/assets/38420974/34d1b5e2-cb03-49d1-b3e6-0f1a61602dcc

**Comment by MarcoFrasca** [comment]
This is the right video https://github.com/pixelfed/pixelfed-rn/assets/38420974/d5e04d59-6c58-48e4-aba7-0159c7c2a829

**Comment by andre-dierker** [comment]
On Android I can see the loading spinner and a movement too.

**Comment by tt-tsquared** [comment]
Yeah came to report this same bug. Latest version of iOS app.

**Comment by MarcoFrasca** [comment]
@dansup fixed on iOS on version 1.0.0.62! 😁
