### ISSUE TITLE
I cant use different image aspect ratio than a square

### ISSUE THREAD

**Issue by alvarokrn** [pixelfed/pixelfed-rn#58]
If I try to upload a new photo Im not able to use a different image aspect ratio than squares.

**Comment by Johnfilmnerd** [comment]
You can drag the cropping square around by the corners to change the aspect ratio.

**Comment by dansup** [comment]
The cropping feature is now disabled by default on the upcoming build, but you can do this yourself by tapping the Gear icon on the top left and uncheck "Enable Media Editor"
