### ISSUE TITLE
Settings crash

### ISSUE THREAD

**Issue by podycust** [pixelfed/pixelfed-rn#60]
![IMG_2432](https://github.com/pixelfed/pixelfed-rn/assets/362102/aebae645-b2e7-4c86-8ee4-37fe878a6542)
tapping server name from settings causes the app to crash!

**Comment by dansup** [comment]
What is your default browser?

**Comment by podycust** [comment]
> What is your default browser?

Safari

**Comment by weddige** [comment]
Same on Android with Vivaldi as default browser.

**Comment by dansup** [comment]
This means your server is running an older version and is missing newer apis.

Please update to v0.12.1 or higher!
