### ISSUE TITLE
no editing in app

### ISSUE THREAD

**Issue by crimperman** [pixelfed/pixelfed-rn#62]
**Android/1.0.0.50:**
I see no option to edit a post in the app. I have to open in browser to do so.
This works but it makes the UX a little clunky and adds extra steps.
![Screenshot_2024-07-02-06-24-37-54_04d1a00dc423a8847c8d557f42f6d70c](https://github.com/pixelfed/pixelfed-rn/assets/54377560/e7e91312-295a-40b9-9091-42df7d477408)

**Comment by dansup** [comment]
Post Editing has been shipped in v1.0.0.65
