### ISSUE TITLE
Discover header

### ISSUE THREAD

**Issue by individual8** [pixelfed/pixelfed-rn#65]
In the current build 1.0.0 (released to the Google Play Store), I found the Discover tab with a monstrous header that reaches into the notification bar.

![Screenshot_20240702-085955](https://github.com/pixelfed/pixelfed-rn/assets/363356/eabc0fbc-7f55-4f4a-b9bb-2ae48d59a8d3)

**Comment by dansup** [comment]
This will be fixed in the next build!

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by individual8** [comment]
![Screenshot_20240816-150548.png](https://github.com/user-attachments/assets/1a339aac-cb34-4117-bca9-16a83a8acf93)

I think this still needs some work. Header scrolls into the OS top bar.
