### ISSUE TITLE
Crashing in different places when navigating the app.

### ISSUE THREAD

**Issue by DKMellow** [pixelfed/pixelfed-rn#7]
Hi, love that the beta app is finally out but I am having issues with the app crashing even navigating to the user discovery page or to display name settings.

I am on a Pixel 6 Pro running graphene os, but the full details of my device should be alongside the log below. Thank you very much and hopefully my bug report helps.

[crash-com-pixelfed-android-26_06-13-34-39_253.zip](https://github.com/user-attachments/files/15987309/crash-com-pixelfed-android-26_06-13-34-39_253.zip)

**Comment by DeadSuperHero** [comment]
Yep, same behavior here, on Android 14 using Samsung Galaxy S23 Ultra

**Comment by justdaj** [comment]
Same for me

**Comment by dansup** [comment]
Fixed in latest commits!
