### ISSUE TITLE
Cannot view individuals profile. Clicking on their avatar sends you to a blank page.

### ISSUE THREAD

**Issue by kgSignal** [pixelfed/pixelfed-rn#70]
I am currently experiencing this issue. I force closed and cleared app cache and the profile views still do not work.

Pixel 7Pro with June security update.

_Originally posted by @kgSignal in https://github.com/pixelfed/pixelfed-rn/issues/37#issuecomment-2203240227_

**Comment by earth-walker** [comment]
I have this issue intermittently, sometimes it works and sometimes it doesn't. After tapping an avatar and getting a blank page as described, I go back to the previous page and the profile page flashes for a brief moment before returning to the feed view. So evidently it is loading the profile page, but it is not being displayed correctly.

**Comment by dansup** [comment]
Fixed in the latest commits!

**Comment by Monstanner** [comment]
In which version was the bug fixed? Because in 1.0.0.68 on Androis 13 Vanilla the bug is "back". However, if you go to a profile, then minimize Pixelfed and then go back into Pixelfed, the profile is displayed correctly.
