### ISSUE TITLE
Direct message crash 

### ISSUE THREAD

**Issue by blueberrie231** [pixelfed/pixelfed-rn#75]
I tried to send a direct message to my partner however when I clicked on his profile then clicked message, when I try to type the message the app instantly crashes so I can't send any direct messages

**Comment by abnerhale** [comment]
It works for me.

Google Beta 1.0.0.50
Android 13
MIUI 14.0.7

**Comment by blueberrie231** [comment]
Sorry it's working now I hadn't updated the app 🤣
