### ISSUE TITLE
cannot post any more to pixelfed.fr

### ISSUE THREAD

**Issue by jlebleu** [pixelfed/pixelfed-rn#76]
With the last update form 1 jul I cannot post any more to pixelfed.fr server a message saying that the server is running an outdated version 
But it seems that pixelfed.fr is updated to the last tag

**Comment by dansup** [comment]
Please uninstall the outdated version and grab the new updated app from https://play.google.com/apps/testing/com.pixelfed

**Comment by jlebleu** [comment]
Done it works thank you
