### ISSUE TITLE
Bug: Posting doesn't work

### ISSUE THREAD

**Issue by Skivling** [pixelfed/pixelfed-rn#91]
I am running v1.0.0.65 on a Samsung Android phone.
I was able to write the post, attach media, write alt text etc. After I pressed post, it said 'posting, please wait.' and a few seconds later it brought me to the main feed with 'uploading new post, please wait' at the top. After that disappeared, it refreshed the feed but my recent post was gone and didn't post.
I waited for a couple hours and checked back on it and it had not posted on the app and I couldn't find it on web either.

**Comment by 9Rk1ng** [comment]
This also happens on iOS 1.0.0.65 but not every time. Trying to work out the circumstances when it does happen

**Comment by Skivling** [comment]
Ok, so it's not just me 😂 - it happens every time for me, I currently can't post from the app.

**Comment by Skivling** [comment]
This may have been an issue with the backend. It wasn't working in Pixelfed app, Pixeldroid, nor web app previously. I believe it is fixed now because I successfully made my first post!
I had been getting an error code beginning with 500, don't remember the other numbers in it.

**Comment by 9Rk1ng** [comment]
I’ve changed to Impressia and that post perfectly.
