### ISSUE TITLE
Bug: Follow hashtag button is missing

### ISSUE THREAD

**Issue by Skivling** [pixelfed/pixelfed-rn#93]
I am running v1.0.0.65 on a Samsung Android phone. I have uninstalled + reinstalled several times from google play, fdroid and direct download, but it hasn't been fixed.
This issue existed a while ago and I reported it on Matrix. Back then, other people didn't have the issue. I'm opening here to make sure it's not forgotten.

For me, going onto a hashtag page will only show the counter of the posts, and no button to follow the hashtag. It should be visible, not sure why it's not.
![Screenshot_20240719_232615_pixelfed](https://github.com/user-attachments/assets/1a59d355-9861-40aa-aeaf-70964982bb51)

**Comment by dansup** [comment]
What is the pixelfed server version?

**Comment by Beleggrodion** [comment]
I have the same issue. My account is on pixelfed.de . On the about page in the footer i see "v0.12.3". Mobile App (from Google Playstore) says 1.0.0.65.

**Comment by Skivling** [comment]
My server is on v0.12.3 as well.

**Comment by dansup** [comment]
Fixed!
